# Getting Started with Pytorch

#### ---Pytorch Packages
#### ---Tensors
#### ---Creating Tensors
#### ---Reshaping Tensors
#### ---Cloning Tensors
#### ---Numeric Datatypes
#### ---Tensors Indexing
#### ---Numpy to Pytorch and Vice Versa
#### ---Squeezing and Unsqueezing Tensors
#### ---Concatenating Tensors
#### ---Stacking Tensors
#### ---Arithematic & Logical Operations
#### ---Using a GPU
#### ---Flattening a Tensor
#### ---Other important operations



In [1]:
import numpy as np
import torch

 Check pytorch versions

In [2]:
print('Pytorch version : ', torch.__version__)

Pytorch version :  1.4.0


In [3]:
torch.cuda.is_available()

False

### Pytorch Packages

torch               ==>      The top-level PyTorch package and tensor library.

torch.nn            ==>      A subpackage that contains modules and extensible classes for building neural                                      networks.

torch.autograd      ==>      A subpackage that supports all the differentiable Tensor operations in PyTorch.

torch.nn.functional ==>      A functional interface that contains typical operations used for building neural                                  networks like loss functions, activation functions, and convolution operations.

torch.optim         ==>      A subpackage that contains standard optimization operations like SGD and Adam.

torch.utils         ==>      A subpackage that contains utility classes like data sets and data loaders that make                              data preprocessing easier.

torchvision         ==>      A package that provides access to popular datasets, model architectures, and image                                transformations for computer vision. 

### Tensors

Fundamental unit of data structure in Pytorch is tensors. Compared with NumPy arrays, PyTorch tensors have a few superpowers, such as the ability to perform fast operations on graphical processing units (GPUs), to distribute operations on multiple devices or machines, and to keep track of the graph of computations that created them. All these features are important in implementing a
modern deep learning library.
Tensors are multidimensional arrays or nd-arrays for short. The reason we say a tensor is a generalization is because we use the word tensor for all values of n like so:

==>A scalar is a 0 dimensional tensor

==>A vector is a 1 dimensional tensor

==>A matrix is a 2 dimensional tensor

==>A nd-array is an n dimensional tensor

##### Rank of a Tensor
A tensor's rank tells us how many indexes are needed to refer to a specific element within the tensor. 

##### Axes of a Tensor
An axis of a tensor is a specific dimension of a tensor. 

##### Shape of a tensor
The shape of a tensor gives us the length of each axis of the tensor. 


### Creating Tensors

torch.tensor(list) - creates tensor of datatype same as list

In [4]:
t = torch.tensor([1, 5, 8, 9, 0])
t

tensor([1, 5, 8, 9, 0])

In [5]:
t = torch.tensor([[1, 5, 8, 9, 0], [2, 5, 6, 3, 9]])
t

tensor([[1, 5, 8, 9, 0],
        [2, 5, 6, 3, 9]])

In [6]:
t.shape

torch.Size([2, 5])

torch.Tensor(list) - create tensor of datatype float

In [7]:
t = torch.Tensor([1, 5, 8, 9, 0])
t

tensor([1., 5., 8., 9., 0.])

In [8]:
t = torch.Tensor([[1, 5, 8, 9, 0], [2, 5, 6, 3, 9]])
t

tensor([[1., 5., 8., 9., 0.],
        [2., 5., 6., 3., 9.]])

torch.ones(shape) - create tensor consisting of 1s of given shape

In [9]:
t =  torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [10]:
t =  torch.ones(2, 5)
t

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

torch.zeros(shape) - create tensor consisting of 0s of given shape

In [11]:
t = torch.zeros(5)
t

tensor([0., 0., 0., 0., 0.])

In [12]:
t = torch.zeros(2,5)
t

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

### Reshaping Tensor

Tensors are stored in contigious location in memory in a single array. Size information is maintained by three more variables namely size, storage offset and stride. The size (or shape, in NumPy parlance) is a tuple idicating how many elements across each dimension the tensor represents. The storage offset is the index in the storage that corresponds to the first element in the tensor. The stride is the number of elements in the storage that need to be skipped to obtain the next element along each dimension. Accessing an element i, j in a 2D tensor results in accessing the storage_offset + stride[0] * i + stride[1] * j element in the storage.

In [13]:
t = torch.tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]])
print(t)
print(t.shape)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
torch.Size([1, 12])


In [14]:
t1 = t.reshape(2,6)
print(t1)
print(t1.shape)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
torch.Size([2, 6])


In [15]:
t1 = t.reshape(3,4)
print(t1)
print(t1.shape)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
torch.Size([3, 4])


In [16]:
t1 = t.reshape(4,3)
print(t1)
print(t1.shape)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
torch.Size([4, 3])


In [17]:
t1 = t.reshape(6,2)
print(t1)
print(t1.shape)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])
torch.Size([6, 2])


### Cloning Tensors

If you use a tensor to assign value to a new tensor, it copy the refrrence rather that creating a copy of data. So, any change in original tensor would be reflected in original tensor and vice versa. To make a copy, we use clone.

In [18]:
#create a tensor
t = torch.ones(3,4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
#assign value to new tensor using original tensor
t1 = t[1]
t1

tensor([1., 1., 1., 1.])

In [20]:
#make change in original tensor
t[1][0] = 100
t

tensor([[  1.,   1.,   1.,   1.],
        [100.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.]])

In [21]:
#changes reflected in new tensor
t1

tensor([100.,   1.,   1.,   1.])

In [22]:
#Now, let do same thing by creating a clone instead of assigning
t = torch.ones(3,4)
t1 = t[1].clone()
t[1][0] = 100
print('t : ', t)
print('t1 : ',t1)

t :  tensor([[  1.,   1.,   1.,   1.],
        [100.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.]])
t1 :  tensor([1., 1., 1., 1.])


### Numeric Datatypes

In [23]:
t =  torch.tensor([1,2,3], dtype= torch.float32)
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [24]:
t =  torch.ones((2,4), dtype= torch.int32)
print(t)
print(t.dtype)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
torch.int32


### Tensors Indexing

It s similar to numpy indexing. Here are a few examples

In [25]:
t = torch.randn((6,6), dtype=torch.float)
t

tensor([[-1.1490, -1.3199,  2.4762,  1.2706, -0.0756,  0.8935],
        [-0.1020, -0.2670,  1.6395, -0.2621, -1.1083, -1.0165],
        [-0.3235, -0.7428,  0.0430,  0.1984, -0.6850, -1.4141],
        [ 1.2443, -0.2294,  1.0594, -0.3388,  0.3721,  1.2341],
        [ 0.7832, -2.1094,  0.3101,  1.8629, -1.5745, -1.1759],
        [-0.4602, -0.1969, -0.8087, -0.2463, -0.0309,  0.8013]])

In [26]:
#all rows one column
t[:,0]

tensor([-1.1490, -0.1020, -0.3235,  1.2443,  0.7832, -0.4602])

In [27]:
#all columns one row
t[0,:]

tensor([-1.1490, -1.3199,  2.4762,  1.2706, -0.0756,  0.8935])

In [28]:
# ith row, jth column

print(t[2][3])

print(t[2,3])

tensor(0.1984)
tensor(0.1984)


In [29]:
# row 0 to 2, column 2, 4
print(t[0:2, 2:4])

tensor([[ 2.4762,  1.2706],
        [ 1.6395, -0.2621]])


In [30]:
# all ropws and from first column to one before last column
t[:,:-1]

tensor([[-1.1490, -1.3199,  2.4762,  1.2706, -0.0756],
        [-0.1020, -0.2670,  1.6395, -0.2621, -1.1083],
        [-0.3235, -0.7428,  0.0430,  0.1984, -0.6850],
        [ 1.2443, -0.2294,  1.0594, -0.3388,  0.3721],
        [ 0.7832, -2.1094,  0.3101,  1.8629, -1.5745],
        [-0.4602, -0.1969, -0.8087, -0.2463, -0.0309]])

### Numpy to Pytorch and Vice Versa

##### Copies data

torch.tensor(data)

torch.Tensor(data)

##### Shares data

torch.as_tensor(data)

torch.from_numpy(data)

In [31]:
data = np.random.randn(3,4)
data

array([[-0.23653952,  1.77608936,  0.17587083, -0.81429013],
       [ 0.55348033,  0.05656446, -0.19696246, -0.94315491],
       [ 0.19164069, -0.85753772,  0.32068837,  0.50057101]])

In [32]:
#create a tensor by methods that copies
t = torch.tensor(data)
print(t)
#make change in new tensor
t[0,0] = 0
print('\n',t)
#change not reflected
print('\n',data)

tensor([[-0.2365,  1.7761,  0.1759, -0.8143],
        [ 0.5535,  0.0566, -0.1970, -0.9432],
        [ 0.1916, -0.8575,  0.3207,  0.5006]], dtype=torch.float64)

 tensor([[ 0.0000,  1.7761,  0.1759, -0.8143],
        [ 0.5535,  0.0566, -0.1970, -0.9432],
        [ 0.1916, -0.8575,  0.3207,  0.5006]], dtype=torch.float64)

 [[-0.23653952  1.77608936  0.17587083 -0.81429013]
 [ 0.55348033  0.05656446 -0.19696246 -0.94315491]
 [ 0.19164069 -0.85753772  0.32068837  0.50057101]]


In [33]:
#create a tensor by methods that shares data
t = torch.as_tensor(data)
print(t)
#make change in new tensor
t[0,0] = 0
print('\n',t)
#change reflected
print('\n',data)

tensor([[-0.2365,  1.7761,  0.1759, -0.8143],
        [ 0.5535,  0.0566, -0.1970, -0.9432],
        [ 0.1916, -0.8575,  0.3207,  0.5006]], dtype=torch.float64)

 tensor([[ 0.0000,  1.7761,  0.1759, -0.8143],
        [ 0.5535,  0.0566, -0.1970, -0.9432],
        [ 0.1916, -0.8575,  0.3207,  0.5006]], dtype=torch.float64)

 [[ 0.          1.77608936  0.17587083 -0.81429013]
 [ 0.55348033  0.05656446 -0.19696246 -0.94315491]
 [ 0.19164069 -0.85753772  0.32068837  0.50057101]]


In [34]:
#To covert tensor to numpy array
arr = t.numpy()
arr

array([[ 0.        ,  1.77608936,  0.17587083, -0.81429013],
       [ 0.55348033,  0.05656446, -0.19696246, -0.94315491],
       [ 0.19164069, -0.85753772,  0.32068837,  0.50057101]])

In [36]:
#change in numpy array
arr[0,1] = 22
arr

array([[ 0.        , 22.        ,  0.17587083, -0.81429013],
       [ 0.55348033,  0.05656446, -0.19696246, -0.94315491],
       [ 0.19164069, -0.85753772,  0.32068837,  0.50057101]])

In [37]:
#change reflected in numpy
t[0,1]

tensor(22., dtype=torch.float64)

In [49]:
arr2 = t.numpy()
arr2 = np.array(arr2)

In [50]:
#make change in numpy array
arr2[0,1] = 23
arr2[0,1]

23.0

In [51]:
#change not reflected
t[0,1]

tensor(11., dtype=torch.float64)

### Squeezing and Unsqueezing Tensors


Squeezing a tensor removes the dimensions or axes that have a length of one.

Unsqueezing a tensor adds a dimension with a length of one.


In [34]:
t = torch.ones(1,5)
print(t)
print(t.shape)

tensor([[1., 1., 1., 1., 1.]])
torch.Size([1, 5])


In [35]:
#squeezing tensor removes one dimension rom tensor
t1 = t.squeeze()
print(t1)
print(t1.shape)

tensor([1., 1., 1., 1., 1.])
torch.Size([5])


In [36]:
#Unsqueezing by putting one more dimention at 0th dimension
t1 = t1 = t.unsqueeze(dim=0)
print(t1)
print(t1.shape)

#Unsqueezing by putting one more dimention at 1st dimension
t1 = t1 = t.unsqueeze(dim=1)
print('\n',t1)
print(t1.shape)

#Unsqueezing by putting one more dimention at 2nd dimension
t1 = t1 = t.unsqueeze(dim=2)
print('\n',t1)
print(t1.shape)

tensor([[[1., 1., 1., 1., 1.]]])
torch.Size([1, 1, 5])

 tensor([[[1., 1., 1., 1., 1.]]])
torch.Size([1, 1, 5])

 tensor([[[1.],
         [1.],
         [1.],
         [1.],
         [1.]]])
torch.Size([1, 5, 1])


### Concatenating tensors

We combine tensors using the cat() function, and the resulting tensor will have a shape that depends on the shape of the two input tensors.


In [37]:
t1 = torch.tensor([[1,5],[8,9]])
t2 = torch.eye(2)
print(t1)
print(t2)

tensor([[1, 5],
        [8, 9]])
tensor([[1., 0.],
        [0., 1.]])


In [38]:
torch.cat((t1,t1), dim=0)

tensor([[1, 5],
        [8, 9],
        [1, 5],
        [8, 9]])

In [39]:
torch.cat((t1,t1), dim=1)

tensor([[1, 5, 1, 5],
        [8, 9, 8, 9]])

### Stacking Tensors

In [40]:
t1 = torch.eye(2)
t2 = torch.ones(2,2)
t3 = torch.zeros(2,2)
print(t1)
print(t2)
print(t3)

tensor([[1., 0.],
        [0., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [41]:
torch.stack((t1, t2, t3))

tensor([[[1., 0.],
         [0., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.]]])

In [42]:
torch.stack((t1, t2, t3)).shape

torch.Size([3, 2, 2])

### Arithematic & Logical Operations

In [43]:
t1 = torch.eye(2)
t2 = torch.ones(2,2)
print(t1)
print(t2)

tensor([[1., 0.],
        [0., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [44]:
#Element wise addition
print(t1+t2)
print(t1.add(t2))

tensor([[2., 1.],
        [1., 2.]])
tensor([[2., 1.],
        [1., 2.]])


In [45]:
#Element wise subtraction
print(t1-t2)
print(t1.sub(t2))

tensor([[ 0., -1.],
        [-1.,  0.]])
tensor([[ 0., -1.],
        [-1.,  0.]])


In [46]:
#Element wise multiplication
print(t1*t2)
print(t1.mul(t2))

tensor([[1., 0.],
        [0., 1.]])
tensor([[1., 0.],
        [0., 1.]])


In [47]:
#Element wise division
print(t1/t2)
print(t1.div(t2))

tensor([[1., 0.],
        [0., 1.]])
tensor([[1., 0.],
        [0., 1.]])


In [48]:
t1 = torch.randn(2,3)
t2 = torch.randn(3,4)
print(t1)
print(t2)

tensor([[ 0.6940, -0.8555, -0.3968],
        [-0.3961,  1.1634, -0.3698]])
tensor([[ 0.0335,  1.5297, -0.5643,  0.8428],
        [ 0.5113,  0.8004,  0.1966,  1.4296],
        [ 0.6278, -0.5025, -0.1809, -0.5126]])


In [49]:
#Matrix Multiplication
torch.matmul(t1,t2)

tensor([[-0.6633,  0.5763, -0.4880, -0.4347],
        [ 0.3494,  0.5112,  0.5191,  1.5190]])

In [50]:
t = torch.eye(2)

In [51]:
#equals to
t.eq(0)

tensor([[False,  True],
        [ True, False]])

In [52]:
#greater than equals to
t.ge(0)

tensor([[True, True],
        [True, True]])

In [53]:
#greater than
t.gt(0)

tensor([[ True, False],
        [False,  True]])

In [54]:
#less than equals to
t.le(0)

tensor([[False,  True],
        [ True, False]])

In [55]:
#less than
t.lt(0)

tensor([[False, False],
        [False, False]])

In [56]:
t1 = torch.eye(2)
t2 = torch.ones(2,2)

In [57]:
t1<=t2

tensor([[True, True],
        [True, True]])

In [58]:
t1==t2

tensor([[ True, False],
        [False,  True]])

### Using a GPU

To use a GPU, you need to send tensor to the GPU device namely 'cuda'

In [59]:
device  = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [60]:
t = torch.tensor([[1,2],[2,3]], device=device)
t

tensor([[1, 2],
        [2, 3]])

In [61]:
t = torch.tensor([[1,2],[2,3]]).to(device)
t

tensor([[1, 2],
        [2, 3]])

In [62]:
t = torch.tensor([[1,2],[2,3]]).cuda()
t

tensor([[1, 2],
        [2, 3]])

In [63]:
t = torch.tensor([[1,2],[2,3]]).cuda()
t

tensor([[1, 2],
        [2, 3]])

### Flattening a Tensor

It is the process of converting a multidimentional array to a one dimentional array. We can also mention start_dim to specify that dimension from which we start flattening tensor

In [64]:
t = torch.empty(2,3,4).normal_(mean=0,std=1)
t

tensor([[[ 1.0591, -1.1709, -0.5956, -0.0351],
         [-0.5657, -1.3186, -1.8893, -0.4637],
         [ 1.7192,  2.0543, -1.2982,  0.9761]],

        [[ 1.5642, -0.4332, -0.2552,  0.8541],
         [-1.3210, -0.1880, -0.4967,  2.5834],
         [-0.7808, -1.4271, -0.4132, -0.7121]]])

In [65]:
torch.flatten(t)

tensor([ 1.0591, -1.1709, -0.5956, -0.0351, -0.5657, -1.3186, -1.8893, -0.4637,
         1.7192,  2.0543, -1.2982,  0.9761,  1.5642, -0.4332, -0.2552,  0.8541,
        -1.3210, -0.1880, -0.4967,  2.5834, -0.7808, -1.4271, -0.4132, -0.7121])

In [66]:
torch.flatten(t,start_dim=1)

tensor([[ 1.0591, -1.1709, -0.5956, -0.0351, -0.5657, -1.3186, -1.8893, -0.4637,
          1.7192,  2.0543, -1.2982,  0.9761],
        [ 1.5642, -0.4332, -0.2552,  0.8541, -1.3210, -0.1880, -0.4967,  2.5834,
         -0.7808, -1.4271, -0.4132, -0.7121]])

### Other important operations

##### 1-D tensor

In [67]:
t = torch.randn(10)
t

tensor([-1.4419,  1.9182,  0.6474, -0.3975, -1.6767,  0.3167,  0.2434,  0.3877,
         1.4522,  0.0276])

In [68]:
#To find max
torch.max(t)

tensor(1.9182)

In [69]:
#To find min
torch.min(t)

tensor(-1.6767)

In [70]:
#To find index with max value
torch.argmax(t)

tensor(1)

In [71]:
#To find index with min value
torch.argmin(t)

tensor(4)

In [72]:
#To find mean of tensor
torch.mean(t)

tensor(0.1477)

In [73]:
#To find std dev
torch.std(t)

tensor(1.1229)

In [74]:
#To find norm
torch.norm(t)

tensor(3.4010)

In [75]:
#To find absolute values
torch.abs(t)

tensor([1.4419, 1.9182, 0.6474, 0.3975, 1.6767, 0.3167, 0.2434, 0.3877, 1.4522,
        0.0276])

In [76]:
#Various trigonometric operations
print(torch.sin(t))
print(torch.cos(t))
print(torch.tan(t))

tensor([-0.9917,  0.9403,  0.6031, -0.3871, -0.9944,  0.3114,  0.2410,  0.3781,
         0.9930,  0.0276])
tensor([ 0.1285, -0.3405,  0.7977,  0.9220, -0.1057,  0.9503,  0.9705,  0.9258,
         0.1183,  0.9996])
tensor([-7.7171, -2.7616,  0.7561, -0.4199,  9.4054,  0.3277,  0.2483,  0.4084,
         8.3921,  0.0276])


##### n-D tensor

Let's understand n-D tensors by taking example of a 3-D tensor as it will be easier to visualize. Consider a 3-D tensor with shape (k,l,m), it can be view in the following ways:

##### k arrays of shape (l,m)
##### l arrays of ahape (k,m)
##### m arrays of shape (k,l)

Also, we can consider it in reverse also. consider example of 'k arrays of shape (l,m)', each of the k arrays wil have lxm elements. So, it can be viewed as lxm arrays each of dimention k. Pytorch view it in similar way when we apply operation on a tensor in a specific dimension. For example, if we have an array of (3,4,5) shape and we apply max operation in dim=0, pytorch will view it as 4x5=20 arrays each of dimension 3 and apply max operation on these 20 arrays. It will return max value as well as corresponding index for each of the 20 arrays.

We can extend it to n-Dimentional tensors. Consider a n-D tensors and we are applying an operation in dim=d, let length of dth axis is k. Let total number of elements in tensor be N. Then, pytorch view it as a (N/k) arrays each of length k. Operation will be applied on each of the (N/k) arrays. Lets look at a few examples of the same.


In [77]:
t = torch.randn(3,4,5)
t

tensor([[[-0.7178, -1.5976,  0.1168, -0.7798,  0.3808],
         [ 1.0398,  0.9831, -0.7171,  0.1001, -0.5136],
         [ 1.2248, -0.0188,  1.3127, -0.2996, -1.0734],
         [ 0.9118,  0.2335, -1.7371, -0.6636, -0.0652]],

        [[ 0.4494,  0.1709,  0.8579, -1.1560,  0.1485],
         [ 1.3072, -0.1976, -0.9659,  1.4372, -2.3819],
         [ 0.2784, -2.5609,  0.6081, -0.1662, -0.1709],
         [-0.8345,  1.1040,  1.8747, -0.0218,  0.9913]],

        [[-0.6245,  0.5121, -0.5450, -1.4153,  0.0926],
         [ 1.2843, -0.1616, -1.0876,  1.1580, -0.7180],
         [ 0.5630,  0.4609,  0.5382,  0.0252,  0.1428],
         [-0.5714,  0.7355,  1.4186, -0.5599, -2.4464]]])

In [78]:
# Max & Min
print(torch.max(t))

print('\n',torch.max(t,dim=0))
print('\n',torch.max(t,dim=1))
print('\n',torch.max(t,dim=2))


print('\n',torch.min(t,dim=0))
print('\n',torch.min(t,dim=1))
print('\n',torch.min(t,dim=2))



tensor(1.8747)

 torch.return_types.max(
values=tensor([[ 0.4494,  0.5121,  0.8579, -0.7798,  0.3808],
        [ 1.3072,  0.9831, -0.7171,  1.4372, -0.5136],
        [ 1.2248,  0.4609,  1.3127,  0.0252,  0.1428],
        [ 0.9118,  1.1040,  1.8747, -0.0218,  0.9913]]),
indices=tensor([[1, 2, 1, 0, 0],
        [1, 0, 0, 1, 0],
        [0, 2, 0, 2, 2],
        [0, 1, 1, 1, 1]]))

 torch.return_types.max(
values=tensor([[1.2248, 0.9831, 1.3127, 0.1001, 0.3808],
        [1.3072, 1.1040, 1.8747, 1.4372, 0.9913],
        [1.2843, 0.7355, 1.4186, 1.1580, 0.1428]]),
indices=tensor([[2, 1, 2, 1, 0],
        [1, 3, 3, 1, 3],
        [1, 3, 3, 1, 2]]))

 torch.return_types.max(
values=tensor([[0.3808, 1.0398, 1.3127, 0.9118],
        [0.8579, 1.4372, 0.6081, 1.8747],
        [0.5121, 1.2843, 0.5630, 1.4186]]),
indices=tensor([[4, 0, 2, 0],
        [2, 3, 2, 2],
        [1, 0, 0, 2]]))

 torch.return_types.min(
values=tensor([[-0.7178, -1.5976, -0.5450, -1.4153,  0.0926],
        [ 1.0398, -0.1976

In [79]:
# In case we want indices only, we can use argmax, argmin
print(torch.argmax(t,dim=1))
print('\n',torch.argmax(t,dim=1))

tensor([[2, 1, 2, 1, 0],
        [1, 3, 3, 1, 3],
        [1, 3, 3, 1, 2]])

 tensor([[2, 1, 2, 1, 0],
        [1, 3, 3, 1, 3],
        [1, 3, 3, 1, 2]])


In [80]:
#Mean
print(torch.mean(t))
print('\n',torch.mean(t,dim=0))

tensor(-0.0385)

 tensor([[-0.2977, -0.3049,  0.1432, -1.1170,  0.2073],
        [ 1.2104,  0.2080, -0.9236,  0.8984, -1.2045],
        [ 0.6887, -0.7063,  0.8197, -0.1469, -0.3672],
        [-0.1647,  0.6910,  0.5188, -0.4151, -0.5068]])


In [81]:
#std dev
print(torch.std(t))
print('\n',torch.std(t, dim=0))

tensor(1.0026)

 tensor([[0.6486, 1.1325, 0.7018, 0.3195, 0.1528],
        [0.1483, 0.6715, 0.1889, 0.7053, 1.0247],
        [0.4856, 1.6239, 0.4284, 0.1633, 0.6314],
        [0.9415, 0.4369, 1.9669, 0.3445, 1.7609]])


In [82]:
#Norm
print(torch.norm(t))
print('\n',torch.norm(t,dim=0))

tensor(7.7070)

 tensor([[1.0523, 1.6864, 1.0230, 1.9868, 0.4191],
        [2.1070, 1.0157, 1.6218, 1.8483, 2.5402],
        [1.3765, 2.6021, 1.5436, 0.3435, 1.0963],
        [1.3617, 1.3469, 2.9231, 0.8685, 2.6404]])


In [83]:
#Absolute Values
print(torch.abs(t))

tensor([[[0.7178, 1.5976, 0.1168, 0.7798, 0.3808],
         [1.0398, 0.9831, 0.7171, 0.1001, 0.5136],
         [1.2248, 0.0188, 1.3127, 0.2996, 1.0734],
         [0.9118, 0.2335, 1.7371, 0.6636, 0.0652]],

        [[0.4494, 0.1709, 0.8579, 1.1560, 0.1485],
         [1.3072, 0.1976, 0.9659, 1.4372, 2.3819],
         [0.2784, 2.5609, 0.6081, 0.1662, 0.1709],
         [0.8345, 1.1040, 1.8747, 0.0218, 0.9913]],

        [[0.6245, 0.5121, 0.5450, 1.4153, 0.0926],
         [1.2843, 0.1616, 1.0876, 1.1580, 0.7180],
         [0.5630, 0.4609, 0.5382, 0.0252, 0.1428],
         [0.5714, 0.7355, 1.4186, 0.5599, 2.4464]]])


In [84]:
#Various trigonometric operations
print(torch.sin(t))
print(torch.cos(t))
print(torch.tan(t))

tensor([[[-0.6577, -0.9996,  0.1165, -0.7032,  0.3716],
         [ 0.8623,  0.8322, -0.6572,  0.0999, -0.4914],
         [ 0.9407, -0.0188,  0.9669, -0.2951, -0.8788],
         [ 0.7906,  0.2314, -0.9862, -0.6160, -0.0652]],

        [[ 0.4344,  0.1701,  0.7564, -0.9152,  0.1480],
         [ 0.9655, -0.1963, -0.8226,  0.9911, -0.6887],
         [ 0.2748, -0.5486,  0.5713, -0.1655, -0.1701],
         [-0.7410,  0.8930,  0.9542, -0.0218,  0.8367]],

        [[-0.5847,  0.4900, -0.5184, -0.9879,  0.0925],
         [ 0.9592, -0.1609, -0.8855,  0.9160, -0.6579],
         [ 0.5337,  0.4447,  0.5126,  0.0252,  0.1423],
         [-0.5408,  0.6710,  0.9884, -0.5311, -0.6405]]])
tensor([[[ 0.7532, -0.0268,  0.9932,  0.7110,  0.9284],
         [ 0.5064,  0.5544,  0.7537,  0.9950,  0.8710],
         [ 0.3391,  0.9998,  0.2552,  0.9555,  0.4771],
         [ 0.6123,  0.9729, -0.1655,  0.7878,  0.9979]],

        [[ 0.9007,  0.9854,  0.6541,  0.4030,  0.9890],
         [ 0.2605,  0.9805,  0.5687,  0.